# -*- coding: utf-8 -*-
"""Placement_DL_Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kn92AVoIsSOSn-S_vFbEARnngS8tbA3h
"""

!pip install tensorflow

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

mnist = keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train / 255.0,x_test/255.0

import matplotlib.pyplot as plt
plt.imshow(x_train[2000])

x_train.shape

x_test.shape

y_train[2000]

model = keras.Sequential([
    layers.Flatten(input_shape=(28,28,1)),
    layers.Dense(128,activation='relu'),
    layers.Dense(10,activation='softmax')
])

model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train,y_train,validation_split=0.1,epochs=10)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['training data','validation data'],loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['training data','validation data'],loc = 'lower right')

y_pred = model.predict(x_test)

y_pred[2000]

import numpy as np
y_pred1 = np.argmax(y_pred,axis=1)  # argmax = converts array into a number
y_pred1[2000]

import matplotlib.pyplot as plt
plt.imshow(x_test[2000],cmap='gray')
plt.title(f"y_test: {y_test[2000]} ,y_pred:{y_pred1[2000]}")
plt.show()

from PIL import Image

img = Image.open('/content/drive/MyDrive/Placement/image 3.png').convert('L') # Convert to grayscale

img = img.resize((28, 28))

img_array = np.asarray(img)
img_array = img_array / 255.0 # Normalize to 0-1 range

img_input = img_array.reshape(1, 28, 28)

print("Preprocessed image shape:", img_input.shape)

plt.imshow(img_input[0], cmap='gray')
plt.title("Uploaded Image (preprocessed)")
plt.show()

# Make a prediction
prediction = model.predict(img_input)

# Get the predicted digit (the one with the highest probability)
predicted_digit = np.argmax(prediction)

print(f"The model predicts this image is a: {predicted_digit}")

model.save("mnist_model.h5")







