# -*- coding: utf-8 -*-
"""Placement_DL_Cifar10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tl2ojxRXHajgzt8MkncDsosCrbAgVNkC
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

cifar10 = keras.datasets.cifar10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train,x_test = x_train/255.0,x_test/255.0

import matplotlib.pyplot as plt
plt.imshow(x_train[9267])

x_train.shape

x_test.shape

y_train[9267]

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import models
model = models.Sequential()
model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))

model.summary()

model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10))

model.summary()

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(x_train,y_train,validation_split=0.1,epochs=10)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['training data','validation data'],loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['training data','validation data'],loc = 'lower right')

y_pred = model.predict(x_test)

y_pred[9267]

import numpy as np
y_pred1 = np.argmax(y_pred,axis=1)  # argmax = converts array into a number
y_pred1[9267]

import matplotlib.pyplot as plt
plt.imshow(x_test[9267],cmap='gray')
plt.title(f"y_test: {y_test[9267]} ,y_pred:{y_pred1[9267]}")
plt.show()





