# -*- coding: utf-8 -*-
"""Placement_DL_Mnist_RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i75Lr0qYRowuJ368A9hZ8D4prT09LLHI
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import LSTM

mnist = keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test = x_train / 255.0,x_test/255.0

import matplotlib.pyplot as plt
plt.imshow(x_train[2000])

x_train.shape

x_test.shape

y_train[2000]

model = keras.Sequential([
    layers.Flatten(input_shape=(28,28,1)),
    layers.Dense(128,activation='relu'),
    layers.Dense(10,activation='softmax')
])

model.compile(optimizer='adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train,y_train,validation_split=0.1,epochs=10)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['training data','validation data'],loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['training data','validation data'],loc = 'lower right')

y_pred = model.predict(x_test)

y_pred[2000]

import numpy as np
y_pred1 = np.argmax(y_pred,axis=1)  # argmax = converts array into a number
y_pred1[2000]

import matplotlib.pyplot as plt
plt.imshow(x_test[2000],cmap='gray')
plt.title(f"y_test: {y_test[2000]} ,y_pred:{y_pred1[2000]}")
plt.show()

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import LSTM
from tensorflow.keras import Input,Model
from tensorflow.keras.layers import Dense

input_shape = (28,28)
inputs = Input(shape=input_shape)
rnn_layer = LSTM(128)(inputs)
outputs = Dense(10,activation='softmax')(rnn_layer)
model = Model(inputs=inputs,outputs=outputs)







